In [1]:
# Load the dataset
import pandas as pd
df = pd.read_csv("credit_risk_dataset.csv")

# Dsiplay top 5 rows in the data 
print(df.head())

   person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0
1          21           9600                   OWN                5.0
2          25           9600              MORTGAGE                1.0
3          23          65500                  RENT                4.0
4          24          54400                  RENT                8.0

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1
1   EDUCATION          B       1000          11.14            0
2     MEDICAL          C       5500          12.87            1
3     MEDICAL          C      35000          15.23            1
4     MEDICAL          C      35000          14.27            1

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length
0                 0.59                         Y                           3
1                 0.10                         N                           2
2                 0.57                         N                           3
3                 0.53                         N                           2
4                 0.55                         Y                           4

In [2]:
# How big is my data
df.shape

(32581, 12)

In [3]:
# What types of data am I dealing with and any missing values?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [4]:
#Are there weird numbers or extreme values
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [5]:
print(df.duplicated().sum())

165

In [7]:
# Checking for duplicate rows if they are actually duplicates in the dataset
duplicate_rows = df[df.duplicated()]
duplicate_rows

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
15975,23,42000,RENT,5.0,VENTURE,B,6000,9.99,0,0.14,N,4
15989,23,90000,MORTGAGE,7.0,EDUCATION,B,8000,10.36,0,0.09,N,3
15995,24,48000,MORTGAGE,4.0,MEDICAL,A,4000,5.42,0,0.08,N,4
16025,24,10000,RENT,8.0,PERSONAL,A,3000,7.90,1,0.30,N,3
16028,23,100000,MORTGAGE,7.0,EDUCATION,A,15000,7.88,0,0.15,N,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32010,42,39996,MORTGAGE,2.0,HOMEIMPROVEMENT,A,2500,5.42,0,0.06,N,12
32047,36,250000,RENT,2.0,DEBTCONSOLIDATION,A,20000,7.88,0,0.08,N,17
32172,49,120000,MORTGAGE,12.0,MEDICAL,B,12000,10.99,0,0.10,N,12
32259,39,40000,OWN,4.0,VENTURE,B,1000,10.37,0,0.03,N,16
32279,43,11340,RENT,4.0,EDUCATION,C,1950,NaN,1,0.17,N,11

In [8]:
#Removing employemnt length outlier:emp_length cannot be greater than 60 and person_age cannot be greater than emp_length

df= df[df['person_emp_length'] <= 60]
df = df[df['person_emp_length'] < df['person_age']]
df.shape

(31684, 12)

In [9]:
# Handling age outliers in the dataset by capping: by replacing the outlier ages with the median age
median_age = df[df['person_age'] <= 100]['person_age'].median()

# Replace any age over 100 with calculated median age
df.loc[df['person_age'] > 100, 'person_age'] = median_age

In [10]:
# Handling null values
# In data analytics, missing data handling is called imputation
# Replacing the null values in the loan_interest rate column with median int_rate

median_int_rate = df['loan_int_rate'].median()
df['loan_int_rate'] = df['loan_int_rate'].fillna(median_int_rate)

In [11]:
# Check if there are any null values in emp_length column
null_count_emp_length = df['person_emp_length'].isnull().sum()
print(null_count_emp_length)

0

In [12]:
# Verify the dataset is clean
print(" POST CLEANING CHECK  ")
print("Missing values left: ", df.isnull().sum())
print(df.shape)

 POST CLEANING CHECK
Missing values left:  person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64
(31684, 12)

In [13]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31684.000000,3.168400e+04,31684.000000,31684.000000,31684.000000,31684.000000,31684.000000,31684.000000
mean,27.730400,6.668817e+04,4.782224,9660.211779,11.035054,0.215408,0.169601,5.809462
std,6.212974,6.242527e+04,4.034888,6334.560789,3.070018,0.411112,0.106273,4.060952
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.939600e+04,2.000000,5000.000000,8.490000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.160000,0.000000,0.230000,8.000000
max,94.000000,6.000000e+06,41.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31684 entries, 1 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  31684 non-null  int64
 1   person_income               31684 non-null  int64
 2   person_home_ownership       31684 non-null  object
 3   person_emp_length           31684 non-null  float64
 4   loan_intent                 31684 non-null  object
 5   loan_grade                  31684 non-null  object
 6   loan_amnt                   31684 non-null  int64
 7   loan_int_rate               31684 non-null  float64
 8   loan_status                 31684 non-null  int64
 9   loan_percent_income         31684 non-null  float64
 10  cb_person_default_on_file   31684 non-null  object
 11  cb_person_cred_hist_length  31684 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.1+ MB

In [15]:
# Boolean Filtering or Boolean Indexing
# Creating a subset containing only the defaults
defaults_df=df[df['loan_status']==1]
print(defaults_df.shape)
print(defaults_df)

(6825, 12)
       person_age  person_income person_home_ownership  person_emp_length  \
2              25           9600              MORTGAGE                1.0
3              23          65500                  RENT                4.0
4              24          54400                  RENT                8.0
5              21           9900                   OWN                2.0
6              26          77100                  RENT                8.0
...           ...            ...                   ...                ...
32563          52          71520                  RENT                0.0
32565          57          40000                  RENT                1.0
32571          60          45600                  RENT                1.0
32574          52          65004                  RENT                4.0
32578          65          76000                  RENT                3.0

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
2              MEDICAL          C       5500          12.87            1
3              MEDICAL          C      35000          15.23            1
4              MEDICAL          C      35000          14.27            1
5              VENTURE          A       2500           7.14            1
6            EDUCATION          B      35000          12.42            1
...                ...        ...        ...            ...          ...
32563        EDUCATION          E       7000          16.82            1
32565          MEDICAL          A      15000           8.90            1
32571          VENTURE          B      20000          10.00            1
32574         PERSONAL          D      20000          15.58            1
32578  HOMEIMPROVEMENT          B      35000          10.99            1

       loan_percent_income cb_person_default_on_file  \
2                     0.57                         N
3                     0.53                         N
4                     0.55                         Y
5                     0.25                         N
6                     0.45                         N
...                    ...                       ...
32563                 0.10                         Y
32565                 0.38                         N
32571                 0.44                         N
32574                 0.31                         Y
32578                 0.46                         N

       cb_person_cred_hist_length
2                               3
3                               2
4                               4
5                               2
6                               3
...                           ...
32563                          24
32565                          21
32571                          26
32574                          19
32578                          28

[6825 rows x 12 columns]

In [16]:
# Save the final cleaned dataset for Power BI

df.to_csv('credit_risk_cleaned.csv', index=False)